### PR TITLE
Adding windows platform supporting files

### PR DESCRIPTION
**Pull request by ajumalp**
1. Added windows platform supporting files
2. Made the form to open maximized

### CODE REVIEW

**Comment by ajumalp** [comment]
Fix for issue [Can't run for desktop window #13](https://github.com/abuanwar072/Flutter-Responsive-Admin-Panel-or-Dashboard/issues/13)

**Comment by abuanwar072** [comment]
Thanks 🙏

**Comment by ajumalp** [comment]
> Thanks 🙏

Glad to help 🙂

**Comment by abuanwar072** [comment]
@all-contributors please add @ajumalp for bug, platform

**Pull request merged**
